package:
  name: leptonica
  version: 1.83.0
  description: leptonica compiled package for Wolfi based distros
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - ca-certificates
      - gcc
      - bash
      - gcc-6
      - linux-headers
      - git
      - autoconf
      - coreutils
      - build-base
      - libtool
      - automake
      - make
      - file
      - tiff-dev
      - libpng-dev
      - libjpeg-dev
      - zlib-dev
      - autoconf
      - pkgconf-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/DanBloomberg/leptonica/releases/download/1.83.1/leptonica-1.83.1.tar.gz
      expected-sha256: 8f18615e0743af7df7f50985c730dfcf0c93548073d1f56621e4156a8b54d3dd
  - runs: |
      mkdir -p ${{targets.destdir}}/leptonica ${{targets.destdir}}/usr/local/lib ${{targets.destdir}}/usr/local/include ${{targets.destdir}}/usr/local/bin
      ./configure --prefix=$HOME/local
      make -j$(nproc)
      make install
      cp -R $HOME/local/lib/* ${{targets.destdir}}/usr/local/lib/
      cp -R $HOME/local/include/* ${{targets.destdir}}/usr/local/include/
      cp -R $HOME/local/bin/* ${{targets.destdir}}/usr/local/bin/
