package:
  name: mesa
  version: 24.1.0
  epoch: 0
  description: Mesa DRI OpenGL library
  target-architecture:
    - aarch64
  copyright:
    - license: MIT AND SGI-B-2.0 AND BSL-1.0

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - elfutils-dev
      - eudev-dev
      - expat-dev
      - findutils
      - flex
      - gettext
      - glslang-dev
      - libdrm-dev
      - libtool
      - libva
      - libva-dev
      - libvdpau-dev
      - libx11-dev
      - libxcb-dev
      - libxdamage-dev
      - libxext-dev
      - libxfixes-dev
      - libxml2-dev
      - libxrandr
      - libxrandr-dev
      - libxrender
      - libxrender-dev
      - libxshmfence-dev
      - libxxf86vm-dev
      - llvm16
      - llvm16-dev
      - meson
      - py3-mako
      - py3-markupsafe
      - py3-pygments
      - py3-setuptools
      - python3
      - vulkan-loader
      - wayland-dev
      - wayland-protocols
      - xorgproto
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: b7eac8c79244806b1c276eeeacc329e4a5b31a370804c4b0c7cd16837783f78b
      uri: https://mesa.freedesktop.org/archive/mesa-${{package.version}}.tar.xz

  - runs: |
      export CFLAGS="$CFLAGS -O2 -g1"
      export CXXFLAGS="$CXXFLAGS -O2 -g1"
      export CPPFLAGS="$CPPFLAGS -O2 -g1"

      _dri_driverdir=/usr/lib/xorg/modules/dri
      _gallium_drivers="r300,r600,radeonsi,nouveau,swrast,virgl,zink"
      _vulkan_drivers="amd,swrast"
      _vulkan_layers="device-select,overlay"

      PATH="$PATH:/usr/lib/llvm$_llvmver/bin" \
      meson \
        --prefix=/usr \
        -Ddri-drivers-path=$_dri_driverdir \
        -Dgallium-drivers=$_gallium_drivers \
        -Dvulkan-drivers=$_vulkan_drivers \
        -Dvulkan-layers=$_vulkan_layers \
        -Dplatforms=x11,wayland \
        -Dllvm=enabled \
        -Dshared-llvm=enabled \
        -Dshared-glapi=enabled \
        -Dgbm=enabled \
        -Dglx=dri \
        -Dopengl=true \
        -Dosmesa=true \
        -Dgles1=enabled \
        -Dgles2=enabled \
        -Degl=enabled \
        -Dgallium-extra-hud=true \
        -Dgallium-xa=enabled \
        -Dgallium-vdpau=enabled \
        -Dgallium-va=enabled \
        -Dgallium-nine=true \
        -Dvideo-codecs=h264dec,h264enc,h265dec,h265enc \
        -Db_ndebug=true \
        -Db_lto=false \
        . output

      meson configure --no-pager output
      meson compile -C output

      DESTDIR="${{targets.destdir}}" meson install --no-rebuild -C output

  - uses: strip

data:
  - name: libs
    items:
      gles: libGLES*
      egl: libEGL
      gl: libGL
      glapi: libglapi
      xatracker: libxatracker*
      osmesa: libOSMesa
      gbm: libgbm
      libd3dadapter9: d3d/d3dadapter9

subpackages:
  - range: libs
    name: mesa-${{range.key}}
    description: mesa ${{range.key}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/${{range.value}}.so* ${{targets.subpkgdir}}/usr/lib

  - name: mesa-dev
    pipeline:
      - uses: split/dev
    description: mesa dev

update:
  enabled: true
  release-monitor:
    identifier: 1970
