package:
  name: pandoc
  version: 3.1.4
  description: pandoc compiled package for Wolfi based distros
  target-architecture:
    - amd64
    - aarch64
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/jgm/pandoc/releases/download/3.1.4/pandoc-3.1.4-linux-amd64.tar.gz
      expected-sha256: 0446e131e121622c68b162e37d1c2f7645c1823197b5e3bf4c0b2627fcb2e149
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/local
      tar xvzf pandoc-3.1.4-linux-amd64.tar.gz --strip-components 1 -C "${{targets.destdir}}/usr/local"
