package:
  name: poppler
  version: 23.06.0
  description: poppler compiled package for Wolfi based distros
  target-architecture:
    - x86_64
  copyright:
    - license: GNU General Public License v3.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - boost-dev
      - boost-static
      - wolfi-base
      - ca-certificates
      - gcc
      - openjpeg
      - bash
      - tiff-dev
      - libpng-dev
      - curl-dev
      - zlib-dev
      - cairo-dev
      - gcc-6
      - linux-headers
      - git
      - autoconf
      - coreutils
      - build-base
      - libtool
      - automake
      - make
      - autoconf
      - pkgconf-dev
      - libjpeg-dev
      - cmake
      - freetype-dev
      - fontconfig-dev
      - libjpeg-turbo

pipeline:
  - uses: fetch
    with:
      uri: https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz
      expected-sha256: 66a469b6e608a51f8347236f4912e27dc5c60c60d7d53ae9bfe4683316c6f04c
  - runs: |
      tar -xzf boost_1_82_0.tar.gz
      cd boost_1_82_0/
      ./bootstrap.sh
      ./b2 headers
      cp -r boost /usr/include/
  - uses: fetch
    with:
      uri: https://poppler.freedesktop.org/poppler-23.06.0.tar.xz
      expected-sha256: d38c6b2f31c8f6f3727fb60a011a0e6c567ebf56ef1ccad36263ca9ed6448a65
  - runs: |
      tar -xf poppler-23.06.0.tar.xz
      cd poppler-23.06.0/
      mkdir source
      mv * source || true
      mkdir -p /$[{targets.destdir}]/usr/include
      cmake ./source -DCMAKE_BUILD_TYPE=release
      make -j$(nproc)
      make install
      mkdir -p "${{targets.destdir}}"/usr/local/include "${{targets.destdir}}"/usr/local/bin/ \
        "${{targets.destdir}}"/usr/local/lib64 "${{targets.destdir}}"/usr/local/share/man/man1 \
        "${{targets.destdir}}"/usr/local/lib
      cp -R /usr/local/include/poppler "${{targets.destdir}}"/usr/local/include/
      cp -R /usr/local/bin "${{targets.destdir}}"/usr/local/
      cp -R /usr/local/share/man/man1 "${{targets.destdir}}"/usr/local/share/man/
      cp -R /usr/local/lib64/* "${{targets.destdir}}"/usr/local/lib64/
      cp -R /usr/local/lib/* "${{targets.destdir}}"/usr/local/lib/
