package:
  name: poppler
  version: 23.06.0
  description: poppler compiled package for Wolfi based distros
  target-architecture:
    - amd64
    - aarch64
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - boost-dev
      - boost-static
      - wolfi-base
      - ca-certificates
      - gcc
      - openjpeg
      - bash
      - tiff-dev
      - libpng-dev
      - curl-dev
      - zlib-dev
      - cairo-dev
      - gcc-6
      - linux-headers
      - git
      - autoconf
      - coreutils
      - build-base
      - libtool
      - automake
      - make
      - autoconf
      - pkgconf-dev
      - libjpeg-dev
      - cmake
      - freetype-dev
      - fontconfig-dev
      - libjpeg-turbo

pipeline:
  - runs: |
      cp packages/boost_1_82_0.tar.gz .
      tar -xzvf boost_1_82_0.tar.gz
      cd boost_1_82_0/
      ./bootstrap.sh
      ./b2 headers
      cp -r boost /usr/include/
      cd ..
      wget https://poppler.freedesktop.org/poppler-23.06.0.tar.xz
      tar -xf poppler-23.06.0.tar.xz
      cd poppler-23.06.0/
      mkdir source
      mv * source || true
      mkdir -p /$[{targets.destdir}]/usr/include
      cmake ./source -DCMAKE_BUILD_TYPE=release
      make -j 8
      make install
      mkdir -p "${{targets.destdir}}"/usr/local/include "${{targets.destdir}}"/usr/local/bin/ \
        "${{targets.destdir}}"/usr/local/lib64 "${{targets.destdir}}"/usr/local/share/man/man1 \
        "${{targets.destdir}}"/usr/local/lib
      cp -R /usr/local/include/poppler "${{targets.destdir}}"/usr/local/include/
      cp -R /usr/local/bin "${{targets.destdir}}"/usr/local/
      cp -R /usr/local/share/man/man1 "${{targets.destdir}}"/usr/local/share/man/
      cp -R /usr/local/lib64/* "${{targets.destdir}}"/usr/local/lib64/
      cp -R /usr/local/lib/* "${{targets.destdir}}"/usr/local/lib/
  - runs: |
      wget https://files.pythonhosted.org/packages/fd/c8/2f212ff8f556fee8836a031cdcdac0781d419a9f3f5eb58a71a57e4ae3e7/poppler-utils-0.1.0.tar.gz