name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  setup:
    strategy:
      matrix:
        docker-platform: ["linux/arm64", "linux/amd64"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_ROBOT_TOKEN }}
      - name: Build base images
        run: |
          make build-base-images
        env:
          DOCKER_PLATFORM: ${{ matrix.docker-platform }}

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

